version: "3.8"
services:
  vue:
    container_name: frontend
    image: node:lts-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: "http-server dist"
  json-server:
    container_name: database
    image: node:16
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
    command: "node server.mjs"
volumes:
  node_modules:
  dist:
